FROM arm64v8/ubuntu:20.04

ENV LANG en_US.utf8
ENV DEBIAN_FRONTEND="noninteractive"

RUN apt-get update && apt-get install -y wireguard iproute2 iptables openresolv curl && rm -rf /var/lib/apt/lists/*

COPY entrypoint.sh /entrypoint.sh
COPY run.sh /run.sh

ENTRYPOINT ["/entrypoint.sh"]

CMD ["/bin/sh", "-ec", "while :; do sleep 5 ; done"]